### ISSUE TITLE
CHE2A tracking issue

### ISSUE THREAD

**Issue by boomanaiden154** [boomanaiden154/Notes#16]
Some TODOs for CHE2A (not planned out for the entire quarter):
* [ ] Oxidation rules in `need-to-know.csv`
* [ ] Names of all of the acids as examples in `need-to-know.csv`
* [ ] Figure out a better way to remember strong acids and bases in `need-to-know.csv`
* [ ] Probably reformat `need-to-know.csv` so Anki will pick up $\LaTeX$ formatting.
* [x] Chapter 3.0-3.8 notes
* [x] Chapter 3.7-3.11 notes
* [x] Add diatomic species to Anki deck
* [x] Correct prelecture 4 with mistake in regards to Sulfur being diatomic

**Comment by boomanaiden154** [comment]
Final was today.
