### ISSUE TITLE
21D tracking issue

### ISSUE THREAD

**Issue by boomanaiden154** [boomanaiden154/Notes#5]
The main 21D syllabus is available [here](https://www.math.ucdavis.edu/courses/syllabus_detail?cm_id=57). Here are the textbook sections that need to be covered:

* 15.1 - Double and Iterated Integrals Over Rectangles
* 15.2 - Double Integrals Over General Regions
* 15.3 - Area by Double Integration
* 15.4 - Double Integrals in Polar Form
* 15.5 - Triple Integrals in Rectangular Coordinates
* 15.6 - Moments and Centers of Mass
* 15.7 - Substitutions in Multiple Integrals
* 12.1, 13.1, 13.2 - Review of Vectors (actually do a new article on this)?
* 13.3 - Arc Length in Space
* 13.4 - Curvature and Normal Vectors of a Curve
* 13.5 - Tangential and Normal Components of Acceleration
* 16.1 - Line Integrals
* 16.2 - Vector Fields and Line Integrals: Work, Circulation, and Flux
* 16.3 - Path Independence, Conservative Fields. Potential Functions
* 16.4 - Green's Theorem in the Plane
* 16.5 - Surfaces and Area
* 16.6 - Surface Integrals
* 16.7 - Stokes' Theorem
* 16.8 - The Divergence Theorem and a Unified Theory

Planning on splitting it odd/even. @boomanaiden154 will be doing the following:
* [x] 15.2 - Double Integrals Over General Regions
* [x] 15.4 - Double Integrals in Polar Form
* [ ] 15.6 - Moments and Centers of Mass
* [ ] 12.1, 13.1, 13.2 - Review of Vectors (actually do a new article on this)?
* [ ] 13.4 - Curvature and Normal Vectors of a Curve
* [ ] 16.2 - Vector Fields and Line Integrals: Work, Circulation, and Flux
* [ ] 16.4 - Green's Theorem in the Plane
* [ ] 16.6 - Surface Integrals
* [ ] 16.8 - The Divergence Theorem and a Unified Theory

@justincl2003 will be doing the following:
* [x] 15.1 - Double and Iterated Integrals Over Rectangles
* [x] 15.3 - Area by Double Integration
* [ ] 15.5 - Triple Integrals in Rectangular Coordinates
* [ ] 15.7 - Substitutions in Multiple Integrals
* [ ] 13.3 - Arc Length in Space
* [ ] 13.5 - Tangential and Normal Components of Acceleration
* [ ] 16.1 - Line Integrals
* [ ] 16.3 - Path Independence, Conservative Fields. Potential Functions
* [ ] 16.5 - Surfaces and Area
* [ ] 16.7 - Stokes' Theorem

I'm thinking we'll end up adding some more stuff in between as well in addition to just the textbook content, particularly proofs/derivations of a lot of the result that we'll be seeing in the course.

**Comment by boomanaiden154** [comment]
Might try and put up some nice explanations with solutions for the class HW problems. Whatever I do, I do need to keep track of the stuff somehow:
* [ ] 15.1 - 1,2,4,5,7,9,13,21,23,38 (Jan 9)
* [ ] 15.1 - 41,43,44,45,46,51,59 (Jan 11)
* [ ] 15.2 - 2,3,7,9,11,12 (Jan 13)
* [ ] 15.2 - 14,15a,17,19,24,33,34 (Jan 18)
* [ ] 15.3 - 1,3,4,12,13,18 (Jan 20)
* [ ] 15.4 - 7,8,11,12,17,42 (Jan 23)
* [ ] 15.5 - 2,3,4,11,13,15 (Jan 25)
* [ ] 15.6 - 1,6,8,18,19,44,56 (Jan 27)
* [ ] 15.6 - 21,27,35,56,70 (Jan 30)
* [ ] 15.7 - 1,4,6,8,12,15a,16ab (Feb 1)
* [ ] 13.1 - 1,3,4,6,8,10,12,13,19,33,43,45,48 (Feb 6)
* [ ] 13.2 - 1,2,3,5,7,11,18 (Feb 8)
* [ ] 13.3 - 1,3,6,9,12,14,19,20 (Feb 10)
* [ ] 13.4 - 2,3,9,11,19,21 (Feb 13) (lessons split after the 11th edition, need to be careful here)
* [ ] 16.1 - 1-8,10,17,18,29 (Feb 15)
* [ ] 16.2 - 1,3,4,5,6,7,15,20,22,31,35 (Feb 17)
* [ ] 16.2 - 17,23,27,37,43 (Feb 22)
* [ ] 16.3 - 1,2,3,7,9,13,19,37 (Feb 24)
* [ ] 16.4 - 1,5,7,8,11 (Feb 27)
* [ ] 16.4 - 15,19,22 (Mar 1)
* [ ] 16.5 - 1,3,5,6,7,13,15,17,19,21,24,27 (Mar 3)
* [ ] 16.6 - 1,4,5,9,17,27,30,39 (Mar 6)
* [ ] 16.7 - 1,3,6,7 (Mar 13)
* [ ] 16.7 - 8,1,3,17 (Mar 15)
* [ ] 16.8 - 5,6,7 (Mar 15)
* [ ] 16.8 - 8,14,16,26 (Mar 17)

**Comment by boomanaiden154** [comment]
Final was on Tuesday.
